path:
  ckpt_path: "./output/ckpt/LJSpeech/pretrain"
  log_path: "./output/log/LJSpeech/pretrain"
  result_path: "./output/result/LJSpeech/pretrain"
optimizer:
  batch_size: 6
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 4
  warm_up_step: 10000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.4
d_optimizer:
  d_initial_lr: 0.000001
  d_max_lr: 0.001
  betas: [0.6, 0.998]
cyclic_optimizer:
  A: 0.0008
  gamma: 0.0001
  freq: 0.001
  lambd: 0.00005
  max_lr: 0.002
  min_lr: 0.00002
step:
  total_step: 900000
  log_step: 20     # 200
  synth_step: 20  # 2000
  val_step: 10    # 1000
  save_step: 40 # 5000
  word_step: 5   # 5
  discriminator_step: 2
pretrain: True
loss:
  pros_weight: 0.5
  pitch_energy_weight: 0.5
  full_duration_weight: 0.01
  label_smoothing: 0.05
