path:
  ckpt_path: "./output/ckpt/LJSpeech/pretrain"
  log_path: "./output/log/LJSpeech/pretrain"
  result_path: "./output/result/LJSpeech/pretrain"
optimizer:
  batch_size: 4
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 4
  warm_up_step: 10000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.4
step:
  total_step: 900000
  log_step: 200     # 100
  synth_step: 2000  # 1000
  val_step: 1000    # 1000
  save_step: 5000  # 100000
  word_step: 10   # 10
pretrain: True
