transformer:
  encoder_hidden: 256

prosody_extractor:
  dim_in: 1
  dim_out: 256
  hidden_dim: 8

prosody_predictor:
  sd_dim_in: 512
  si_dim_in: 256
  dim_out: 256
  n_components: 8
  conv_hidden_dim: 8
  gru_hidden_dim: 512
  bigru_hidden_dim: 32

max_seq_len: 1000

text_embedding_dim: 256

pros_learner:
  model: "ProsodyLearner"