path:
  ckpt_path: "./output/ckpt/LJSpeech/train"
  log_path: "./output/log/LJSpeech/train"
  result_path: "./output/result/LJSpeech/train"
optimizer:
  batch_size: 2
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 2     # 100
  synth_step: 3  # 1000
  val_step: 4    # 1000
  save_step: 3  # 100000
  word_step: 4  # 10
pretrain: False