dataset: "Spanish"

path:
  corpus_path: "/home/ditto/Datasets/Speech/es"
  lexicon_path: ""  # Only used in synthesize.py
  raw_path: "/home/ditto/Datasets/FastSpeech2/raw_data/Spanish_new"
  preprocessed_path: "/home/ditto/Datasets/FastSpeech2/preprocessed_data/Spanish_new"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["spanish_cleaners"]
    language: "es"
    target_language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  miipher:
    miipher_path: "miipher/miipher_v2.ckpt"
    vocoder_path: "miipher/vocoder_finetuned_v2.ckpt"
    
